name: Run Unit Tests

on:
  push:
     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    if: github.repository == 'cmlibs-python/cmlibs.exporter'
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.10', '3.11', '3.12']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required system libraries
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libosmesa6 libglu1-mesa -y

      - name: Install dependencies for ${{ matrix.os }} Python ${{ matrix.python-version }}
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            PY_VERSION_NODOT=$(echo "${{ matrix.python-version }}" | tr -d '.')
            WHEEL_URL="https://github.com/cmlibs/swigzinc/releases/download/osmesa/cmlibs_zinc-4.2.1-cp${PY_VERSION_NODOT}-cp${PY_VERSION_NODOT}-linux_x86_64.whl"
            pip install "${WHEEL_URL}"
            pip install -e ".[opengl_software]"
          else
            pip install -e ".[opengl_hardware]"
          fi

      - name: Run unit tests
        run: python -m unittest discover -s tests
