name: Run Unit Tests

on:
  push:
     branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    #if: github.repository == 'cmlibs-python/cmlibs.exporter'
    if: github.repository == 'hsorby/cmlibs.exporter'
    continue-on-error: true
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ['3.9', '3.11', '3.12']
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # configure python
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install required system libraries
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt install libosmesa6 libgl1-mesa libglu1-mesa -y
      # install deps
      - name: Install dependencies for ${{ matrix.os }} Python ${{ matrix.python-version }}
        shell: bash
        run: |
          python -m pip install --upgrade pip
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            pip install -e ".[opengl_software]"
          else
            pip install -e ".[opengl_hardware]"
          fi
          pip uninstall -y cmlibs.zinc
          pip install https://github.com/cmlibs-dependencies/prebuilt-library-cache/releases/download/cache/cmlibs_zinc-4.2.1-cp312-cp312-linux_x86_64.whl

      # find and run all unit tests
      - name: Run unit tests
        run: python -m unittest discover -s tests
